# Generated by Django 4.2.6 on 2023-10-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="member",
            name="profile_img",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="member",
            name="provider",
            field=models.TextField(default="None", max_length=10),
        ),
        migrations.AlterField(
            model_name="member",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
