# Generated by Django 4.2.6 on 2023-10-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_member_id_alter_member_profile_img_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="member",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
