# Generated by Django 4.2.6 on 2023-10-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="vodtest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("apiid", models.IntegerField(max_length=20)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=200, null=True)),
                ("imgpath", models.CharField(max_length=50, null=True)),
                ("category", models.CharField(max_length=10)),
                ("actor", models.CharField(max_length=50, null=True)),
                ("director", models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
